### ISSUE TITLE
Feat(Core): Support infinite buffs for MHR and MHW

### ISSUE THREAD

**Issue by Haato3o** [HunterPie/HunterPie#253]

**Comment by WetU** [comment]
MHR buffs

<DEMON_DRUG>
Offset="7C"
WithValue="5"

<GREAT_DEMON_DRUG>
Offset="7C"
WithValue="7"

<ARMOR_SKIN>
Offset="80"
WithValue="15"

<GREAT_ARMOR_SKIN>
Offset="80"
WithValue="25"
