### ISSUE TITLE
Transparent minimize button

### ISSUE THREAD

**Issue by SypherRed** [HunterPie/HunterPie#298]
Good day, I would like to report that in v2.5.0.xxx, the minimize button went missing and is now transparent with a slight highlight as seen in the screenshot.

Theme is set to "Default".

![fw5ylba4I3](https://user-images.githubusercontent.com/64218204/204019665-7a1ed64e-fbe0-4950-b23d-e67faffabbfb.png)

**Comment by SypherRed** [comment]
Pardon, the highlight could be better addressed as "mouseover" or "hover".

**Comment by Haato3o** [comment]
Hmm, it might be the font your HunterPie is using, can you install [Work Sans](https://fonts.google.com/specimen/Work+Sans) and see if that still happens?

**Comment by SypherRed** [comment]
Yes, seems that the Font was missing through the update for me.
Thank you.
