### ISSUE TITLE
Fix(Core): Having the same name appear twice in one party omits one player from the DPS widget

### ISSUE THREAD

**Issue by Polymeta** [HunterPie/HunterPie#316]
When playing MHR (Sunbreak) and joined a quest via join request, then another player joined who coincendentally had the same name as the host, as you can see in below screenshot, the bowgun player does not show up in the DPS widget, presumably because they have the exact same name as the host.

HunterPie Version: 2.6.0.158

![image](https://user-images.githubusercontent.com/40173118/206437419-d9ee34e9-f583-41d1-bf0a-6b780e80d9d7.png)

**Comment by Haato3o** [comment]
Fixed in #357
