### ISSUE TITLE
Monster parts not showing at all in World

### ISSUE THREAD

**Issue by JCAntunes95** [HunterPie/HunterPie#327]
The monster widget just doesn't show monster parts at all, even when I'm the host or playing solo, in MH World.

I can still see the parts with HunterPie v1.0.5

**Comment by Haato3o** [comment]
As stated in the [documentation](https://docs.hunterpie.com/posts/monster-widget/#monster-parts), you **must** target the monster for it to display the parts.

**Comment by JCAntunes95** [comment]
Ah, I see, so it was changed from the previous version.

Additionally, after going other releases, for some reason it seems like .NET runtime you link to on startup (if it's not installed) doesn't seem to actually make HunterPie v2 work.

When I used the installer release (on Nexus Mods) the .Net version it installs is 6.0.8, and so when I installed that version it worked.

So the version you link to is 6.0.0 (doesn't work).
The installer gives 6.0.8 (works)

**Comment by JCAntunes95** [comment]
After further inspection it might be because he sends me to the ".NET 6.0 Runtime (v6.0.11)" rather than the ".NET 6.0 *Desktop* Runtime (v6.0.11)"

**Comment by Haato3o** [comment]
I don't link any .NET runtime on startup, that's a popup that appears on any .NET application if you don't have the right runtime installed, it was not coded by me.
And it does work, you probably just downloaded the wrong version, HunterPie requires the Desktop Runtime (which is the one linked in Nexus) and not just the Runtime, they're different. The page the popup takes you to has all the different runtimes available.
![image](https://user-images.githubusercontent.com/35552782/206932860-57c6ac09-e3f1-4351-8f83-65382c130171.png)

**Comment by JCAntunes95** [comment]
Ok, so that one is on Microsoft.
The problem I had is that they apparently don't link the Desktop Runtime download, just the Runtime.
![image](https://user-images.githubusercontent.com/25153358/206933199-163c7abc-4e5f-485d-b797-8b02da60fe69.png)

Anyways, thx for the help.
Hope you can keep up the good work.
