### ISSUE TITLE
MHW: More customizable options to Monster Widget needed

### ISSUE THREAD

**Issue by Forien** [HunterPie/HunterPie#349]
1. Option to select specific ailments to be always visible
2. Option to select current target monster by scoutflies, not by manual targeting

**Comment by Haato3o** [comment]
1. Same as #318 
2. Still need to think of a way to implement it in a way that's not hacky

**Comment by nix6839** [comment]
> 2. Still need to think of a way to implement it in a way that's not hacky

I'm interested in the second request. What do you mean "not hacky"?

**Comment by Haato3o** [comment]
> I'm interested in the second request. What do you mean "not hacky"?
I meant that since HunterPie supports both MHW and MHRise, I had to find a way to implement it without affecting the other game, since MHRise does not have scoutflies. Anyways, that was added in v2.10.0
