### ISSUE TITLE
MHW:Always prompt to check local files

### ISSUE THREAD

**Issue by komorebi7369** [HunterPie/HunterPie#352]
After downloading the latest version of v2.6.0 and starting HunterPie.exe under the Windows 10 environment, you will always be prompted: checking for new localization files, restarting the computer and closing the software cannot solve the problem. How to solve this problem
![捕获](https://user-images.githubusercontent.com/41587989/214605935-8f0d0b45-38ac-4397-86e0-70ae4cdef973.PNG)

**Comment by Haato3o** [comment]
Your HunterPie folder is either in read only mode or it doesn't have permissions to write/read files in its folder. Read the [FAQ](https://docs.hunterpie.com/posts/faq/#my-auto-update-is-getting-stuck).
