### ISSUE TITLE
MHW Can't show monster info, just icon

### ISSUE THREAD

**Issue by Levelangel** [HunterPie/HunterPie#353]
versin 2.6.0.163
![image](https://user-images.githubusercontent.com/16518190/214663611-3e0c0619-57bd-4de6-bb61-fda41c7d0f7e.png)

**Comment by Haato3o** [comment]
You changed the theme to "Minimal" instead of the default. Just change it back to default and restart your client.

**Comment by Levelangel** [comment]
Thank you!
