### ISSUE TITLE
Player widget coloring is bugged when using Berserk after update v2.6.0.164

### ISSUE THREAD

**Issue by brokofankone** [HunterPie/HunterPie#361]
I noticed today after HPie auto-updated, that now the health bar of the player widget remains colored RED in both scroll states when using Berserk skill. 

The normal behavior is that your health bar would remain green outside of Berserk, and go into full red color when you enter the berserk state (by switching switch scrolls). You can confirm that's the expected way for it to work by checking the default HUD elements in Rise and switching between the scrolls.

**Comment by Haato3o** [comment]
Fixed in [88fbd1b](https://github.com/HunterPie/HunterPie/commit/88fbd1b2adab9df3c909c9986cb42049c24c707e)

Usually takes 15 minutes for the new binaries to be released in the server, but it will be fixed on v2.6.0.165

**Comment by brokofankone** [comment]
Awesome, that was a quick fix! I can confirm it works as expected on the new build
