### ISSUE TITLE
[Feat Request] Inclusion of Skills such as Intrepid Heart for Abnormality Widget/Player Widget

### ISSUE THREAD

**Issue by VioletRimberg** [HunterPie/HunterPie#372]
It would be nice to be able to track certain armor skills which are currently not included in the HUD.

For Intrepid Heart:

Option 1) Add independent bar for Intrepid Heart Progress 
Option 2) Add a Buff selectable in the Abnormality Widget 

For Dragonheart:

Option 1) Add selectable indicator to show thresh hold for Player Hud Widget
Option 2) Add a buff or debuff selectable in Abnormality Widget to track activation

As is right now, I could not tell whether Intrepid Heart would be active, or if Dragonheart's buffs became active when solely relying on the Player HUD Widget combined with a set up Abnormality Widget for buffs and debuffs.

**Comment by WetU** [comment]
Added Interpid Heart(Buildup) and Dragonheart active state to Abnormality Widget in v2.7.0.
You can update to beta version, If you are patreon.

**Comment by VioletRimberg** [comment]
Thanks for the quick response. I will look forward to v2.7.0!
