### ISSUE TITLE
Fix(Core): Hide widget when UI is visible does not work if user is playing with a controller

### ISSUE THREAD

**Issue by Haato3o** [HunterPie/HunterPie#384]

**Comment by WetU** [comment]
I found bit flags for mouse cursor available.
I haven't tested it to see if it works even when using the pad.

UI_ADDRESS + 0xA28 + 0x10 + 0x20
{
        YNinfo = 1 << 0,
        CommonInfo = 1 << 1,
        NetworkErrorInfo = 1 << 2,
        TutorialWindow = 1 << 3,
        Conversation = 1 << 4,
        KitchenTable = 1 << 5,
        Kitchen = 1 << 6,
        TableAction = 1 << 7,
        Smithy = 1 << 8,
        StartMenu = 1 << 9,
        OptionWindow = 1 << 10,
        DetailMap = 1 << 11,
        ItemBox = 1 << 12,
        Loading = 1 << 13,
        MixMenu = 1 << 14,
        PoseSet = 1 << 15,
        Album = 1 << 16,
        UpdateInfoWindow = 1 << 17,
        HoldBoxChange = 1 << 18,
        TrainingCounter = 1 << 19,
        DLCInfo = 1 << 20,
        HRLimitBreak = 1 << 21,
        ChatMenu = 1 << 22,
        CharacterCreation = 1 << 23,
        TitleFlow = 1 << 24,
        QuestCounter = 1 << 25,
        OtomoBoard = 1 << 26,
        OtomoHire = 1 << 27,
        OtomoDojo = 1 << 28,
        OtomoSpyUnitTitleMenu = 1 << 29,
        OtomoSpyUnitReturn = 1 << 30,
        TradeCenter = 1 << 31
}
--
UI_ADDRESS + 0xA28 + 0x10 + 0x24
{
        ItemShop = 1 << 0,
        PostMan = 1 << 1,
        ItemBoxMenu = 1 << 2,
        LobbyMap = 1 << 3,
        QuestBoard = 1 << 4,
        RoomService = 1 << 5,
        Owl = 1 << 6,
        SideQuestRequestMenu = 1 << 7,
        RewardDialog = 1 << 8,
        ArenaCounter = 1 << 9,
        Camp = 1 << 10,
        SupplyBox = 1 << 11,
        Result = 1 << 12
}

**Comment by Haato3o** [comment]
This issue is for MHW, not MHR.

**Comment by Haato3o** [comment]
fixed in #498
