### ISSUE TITLE
NPC followers not shown correctly in DPS meter while in online lobby

### ISSUE THREAD

**Issue by PotionClair** [HunterPie/HunterPie#398]
Every time I'm in an online lobby and I start a solo quest with AI-controlled NPC followers, the DPS meter seems to malfunction.

Examples (it should show Hinoa and Minoto):

![image](https://user-images.githubusercontent.com/12266606/222785797-00356033-f6a5-41e3-b6f5-f18f7cfc9ee5.png)

![image](https://user-images.githubusercontent.com/12266606/222785831-acfb69f8-711a-429c-9abe-aa3e09e48279.png)

Video: see at ~[19min](https://www.twitch.tv/videos/1754502196?t=0h19m18s) and also ~[2h16min](https://www.twitch.tv/videos/1754502196?t=2h16m40s)

NPC Followers are displayed correctly in the DPS meter when I'm not in an online lobby.

**Comment by Haato3o** [comment]
Will look into it

**Comment by Haato3o** [comment]
Should be fixed in 40d3a0cc380d652c4d88cdb76d1151917faa76f3
