### ISSUE TITLE
MHW: Player info does not include phials

### ISSUE THREAD

**Issue by ConnorPickles** [HunterPie/HunterPie#401]
The play info widget does not include the phial/charge level for charge blade (and I assume other weapons with similar UI). Since World ties this info to the health bar, sharpness, etc., I can't use the HunterPie UI and disable World's player info without losing this important information.

**Comment by Haato3o** [comment]
That's going in the class helpers, which are planned but no ETA yet due to it's complexity and not really a priority for me at the moment.

**Comment by Jeremy-Leo** [comment]
i was a world  new player, by search a lot of info,i find this tool, really need weapon info +1 , what ever thanks
