### ISSUE TITLE
MHW (Bug): DPS meter often doesn't track damage in Guiding Lands

### ISSUE THREAD

**Issue by ConnorPickles** [HunterPie/HunterPie#407]
While hunting in the Guiding Lands, the DPS meter often doesn't track any damage for allies, and sometimes doesn't track damage for the current user either.

I haven't been able to notice any patterns for when this is an issue unfortunately, but if there are specific things I could look for in the future that could help narrow this down I'd be happy to make some notes.

**Comment by Haato3o** [comment]
It's not possible to track other party member damage in guiding land nor expeditions though, not a bug, just a game limitation.

As for not tracking your own damage, that requires you to have HunterPie Native enabled and also Stracker's Loader installed, can you provide a video or something of it not tracking your own damage when you have both of those enabled?
