### ISSUE TITLE
MHW:I - Activities: Broken Botanical Box Counter

### ISSUE THREAD

**Issue by DorkyDuck** [HunterPie/HunterPie#410]
My botanical box is stuck at 1/50 and regardless of what I do it won't go away. Whenever something would cultivate, instead of being 4/50 in the game. The counter for the botanical box would display 5/50 and will be stuck at 49/50 whenever the box gets full.

**Comment by Haato3o** [comment]
Can you provide some screenshot and more details about the issue? I just tested it locally and it's working just fine.
![image](https://user-images.githubusercontent.com/35552782/230708205-a4d63ae2-098e-45ce-9fd9-f49edfd5b069.png)

**Comment by DorkyDuck** [comment]
![mhwi](https://user-images.githubusercontent.com/83339425/230757275-4d08c2a1-dc7e-4b71-95f2-4ed55be017ed.PNG)

Thank you for the quick response, I have tried many things to sort of fix it but it still persisted.

**Comment by Haato3o** [comment]
1. Are you using the slot 1 for your character save?
2. What are you harvesting?
3. Does it also happen in HunterPie v1?

**Comment by DorkyDuck** [comment]
1. I am indeed using slot 1 for my character save.
2. I am harvesting mandragoras
3. The issue does not persist on HunterPie v1

**Comment by Haato3o** [comment]
Will look into it

**Comment by DorkyDuck** [comment]
I've managed to make the displays match but after taking and selling some of the botanical box's contents, the display still went back 1/50.

**Comment by Haato3o** [comment]
Fixed in #461
