### ISSUE TITLE
MHW Iceborne: Monster Widget not working

### ISSUE THREAD

**Issue by itskaoz** [HunterPie/HunterPie#413]
Everything else seems to work. Last update does not show Monster Widget anymore. It's still visible in Design Mode though but empty!

**Comment by De-Ge** [comment]
Same issue here. Everything else seems to be working fine. I have tried it on two computers, both don't show monster information anymore.

**Comment by Haato3o** [comment]
Fixed in 1339cb2e85090350b8265eacf86815a596099291
