### ISSUE TITLE
MHW Iceborne: Monster Widget not working correctly

### ISSUE THREAD

**Issue by JYC333** [HunterPie/HunterPie#426]
Thanks for this tool!

The monster widget doesn't work correctly, I've seen the similar issue #413, but seems still have the problem.

It only shows the monster health bar and doesn't show the monster parts, cannot find the reason after searching around a bit.

**Comment by Haato3o** [comment]
As stated in the [docs](https://docs.hunterpie.com/posts/monster-widget/#targeting-a-monster), you need to target the monster for it to show the monsters's part health.

Also, you **MUST** be party host to be able to see the monster's health, that's a game limitation, not much I can do about that.

**Comment by JYC333** [comment]
Is that possible to show the parts without lock-on system? HunterPie v1 can show the parts all the time when target on a monster whether you lock-on it or not.

**Comment by Haato3o** [comment]
Nope, those were design decisions to avoid cluttering the screen, it's not like people will fight multiple monsters at the same time for the need to track part health for multiple monsters.

What you can do though, is change your target settings to make it not mess with the game at all:
![image](https://user-images.githubusercontent.com/35552782/236716395-6d32464d-a881-4f30-aadf-f1dc74b32b55.png)

**Comment by JYC333** [comment]
Ok, that helps, thanks for answering!
