### ISSUE TITLE
Black screen when launching the Game

### ISSUE THREAD

**Issue by jeyg20** [HunterPie/HunterPie#434]
When launching the game from the HuntersPie app, the game remains on a black screen and I am unable to perform any interactions on my computer.

**Comment by Haato3o** [comment]
Are you talking about MHW or MHR? Launching the game from HunterPie is the exactly same thing as launching it from Steam. If you're talking about MHW and your game is getting stuck in a black screen that is usually related to broken mods in your NativePC folder.

**Comment by jeyg20** [comment]
It is MHW, I thought I had to launch the game from the app, I replicate launching the game from steam with and without mods, and it runs perfectly on both, the black screen only happens from the application.

Thanks for the help

**Comment by Haato3o** [comment]
The launch button on the app is just a QoL, all it does is call steam to launch the game, it's exactly the same thing as launching from steam.

https://github.com/HunterPie/HunterPie/blob/aef90a2da2a438ada8eaa604e9bfc2a42a012da3/HunterPie/Internal/Steam.cs#L24-L28

**Comment by jeyg20** [comment]
I can see that, not sure why in only does that from the app
