### ISSUE TITLE
Feat(Core): Add a clock option to the Player Hud Widget

### ISSUE THREAD

**Issue by muuyo** [HunterPie/HunterPie#435]
Currently, I much prefer the more detailed health and sharpness indicators. Issue: In the default position, it covers the clock.
I can move it, but then it either looks weird or covers my weapon UI (or is somewhere I'm not used to) There's only a clock in the Damage Meter, and not in the player hud - where the weapon icon is - so if I have the damage meter disabled, it's impossible to tell how far into the mission I am without a weird UI layout.
Any chance we could have the option to replace the (somewhat useless) weapon icon with a clock?

**Comment by WetU** [comment]
[NoWeaponIcon.zip](https://github.com/HunterPie/HunterPie/files/11642540/NoWeaponIcon.zip)

Player hud theme without weapon icon.
Use according to HunterPie theme feature.
