### ISSUE TITLE
v2.9.0.117, MHW, Monster Widget: Fails to read correct part damage stats & monster ailments progress more often than not

### ISSUE THREAD

**Issue by GuidoBelluomo** [HunterPie/HunterPie#447]
Part damage stats are stuck at their max values, and progress for monster ailments (such as stun progress, claw flinch, exhaustion) does not show. The widget does however show currently active ailments such as when a monster gets poisoned or stunned.

Not entirely sure how to reproduce it, I've noticed it tends to happen more when I am not the person who started the mission. I have found no workaround nor information that this is normal behaviour. If it is, I apologize 😆

**Comment by Haato3o** [comment]
That's a MHW limitation. You **must** be quest host in order to see the parts health and ailment buildups because only the host has that information in memory, other party members don't receive it.

**Comment by GuidoBelluomo** [comment]
Alright, thank you.

**Comment by GuidoBelluomo** [comment]
Closing
