### ISSUE TITLE
Exported Hunts not refreshing

### ISSUE THREAD

**Issue by Schlurcher** [HunterPie/HunterPie#455]
After finishing a hunt it doesn't show up in exported hunts. I have to close and reopen the client.

Either a force refresh button or an auto refresh would be nice.

**Comment by Haato3o** [comment]
Oh, that seems to be a bug, HunterPie does cache the exported hunts list, but it was supposed to clear the cache after 5 minutes, which is apparently not happening

**Comment by Haato3o** [comment]
Fixed #459
