### ISSUE TITLE
MHW: Blinking HUD on the health bar

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [HunterPie/HunterPie#457]
### Steps to Reproduce
1. Start Monster Hunter World via HunterPie 
2. Start the mission

### Expected Behavior
The health bar should remain stable.

### Actual Behavior
The health bar blinks sporadically.

### System Information
- Operating System: Windows 10
- RAM: 16GB
- Processor: Intel i5-11400F
- Graphics Card: NVIDIA RTX 3060

### Mod Version
HunterPie v2.9.0

### Attachments
https://www.youtube.com/watch?v=qBiNpPeRzGk

**Comment by Haato3o** [comment]
The Charge Blade widget and the health bar widget are overlapping each other, just toggle design mode and move the charge blade widget somewhere else.

**Comment by bhaskoro-muthohar** [comment]
Yes, we need manually to adjust the widget. Thanks 👍🏽
