### ISSUE TITLE
The game update cause hunterpie doesn't work

### ISSUE THREAD

**Issue by wafske** [HunterPie/HunterPie#460]
At 2023.10.17,MHW launched a update and changed file chunk/chunkG9.bin,chunk/chunkG60.bin,MonsterHunterWorld.exe,
steam_api64.dll in game folder,now hunterpie can't connect to the game instance.

**Comment by Haato3o** [comment]
Fixed in #461

**Comment by wafske** [comment]
> Fixed in #461

Great thanks!
