### ISSUE TITLE
some errors, damage meter doesn't work

### ISSUE THREAD

**Issue by 1dkwhoam1** [HunterPie/HunterPie#462]
https://imgur.com/TIDcnr8
idk what does it mean, but damage meter dont work

**Comment by Haato3o** [comment]
I'm working on it already. The latest patch for Monster Hunter World changed a couple stuff internally.

**Comment by 1dkwhoam1** [comment]
ok, sry for wasting ur time

**Comment by bhaskoro-muthohar** [comment]
you don't need to close this issue @1dkwhoam1
