### ISSUE TITLE
MHW Feat(UI) : Use map pin instead of lockon

### ISSUE THREAD

**Issue by AschAuroraVT** [HunterPie/HunterPie#464]
Hello there. I'm sorry if this has been requested, but I've used the old MHW hunterpie and are transitioning to the new hunterpie. While I like and can work with most of the features, may I request that you please implement the 'Use lockon instead of map pin to target monster' toggle similar to the old MHW hunterpie as an option/feature on the new hunterpie?

I love the newer, cleaner and more pleasing UI on the new hunterpie, but using lockon in MHW is making it hard to target specific part on the monster since MHW's lockon always tends to make you target the centre of their body, making target sensitive fights (such as Alatreon fights where the horns are the required target to reset its elemental change) stressful.

Until the implementation is done I'll be using the old one for my hunts. I hope there's no plans on taking the old hunterpie down in the near future.

I'm sorry that a simple request are turning out to be a whole essay. I admire your work and wishing you success in the upcoming future.

**Comment by Haato3o** [comment]
I do want to add that option, but you could also just change the lock-on settings so it won't affect your camera
![image](https://github.com/HunterPie/HunterPie/assets/35552782/7ea437c2-0c84-4046-b861-91ab764f3e3b)

**Comment by AschAuroraVT** [comment]
Thank you for the swift reply.

I will be using the settings suggested and adjust my playstyle accordingly if I'm playing using the new HunterPie at the time of playing until the feature is implemented.

Best of luck and God bless!
