### ISSUE TITLE
[Question] Are the crashes related to HunterPie?

### ISSUE THREAD

**Issue by vavavr00m** [HunterPie/HunterPie#468]
Please see screenshots:

![image](https://github.com/HunterPie/HunterPie/assets/4675132/edda6ed6-23b2-4abf-b80e-bf568623c198)

![image](https://github.com/HunterPie/HunterPie/assets/4675132/f9574714-d7c5-4ed4-8532-bd2b940bc74d)

**Comment by Haato3o** [comment]
@vavavr00m What's your game version?
