### ISSUE TITLE
Monster Size for MHW? 

### ISSUE THREAD

**Issue by hippoopoothomas** [HunterPie/HunterPie#473]
Hello, loving this mod! Any plans to implement monster size into the Monster Widget for MHW? TIA :)

**Comment by Haato3o** [comment]
> Hello, loving this mod! Any plans to implement monster size into the Monster Widget for MHW? TIA :)

What do you mean by monster size? You mean like their crown? Because that has been implemented since forever

**Comment by hippoopoothomas** [comment]
Hi, sorry for the confusion, I meant monster size as in how big the monster is in centimetres

**Comment by Haato3o** [comment]
Why exactly would you want the exact number though? Isn't the crown enough? 🤔

**Comment by hippoopoothomas** [comment]
this stupid scarred yian garuga large crown isn't spawning :( my friends and I want to record the size data to see how close we are getting to the large crown size threshold but I understand if this feature is not planned. Thanks for entertaining this request :^)
