### ISSUE TITLE
 monster stamina and monster parts

### ISSUE THREAD

**Issue by GraspAcao** [HunterPie/HunterPie#485]
![1](https://github.com/HunterPie/HunterPie/assets/64088652/eb717698-ddfa-4edc-852e-1a820611a076)
![2](https://github.com/HunterPie/HunterPie/assets/64088652/4f7a8a65-04c5-47e7-817a-93f9bfd67b02)
Why I can't see the data of monster stamina and monster parts. It's the same with MHW.

**Comment by Haato3o** [comment]
It's explained in the [documentation](https://docs.hunterpie.com/posts/monster-widget/#targeting-a-monster)
