### ISSUE TITLE
Failed to parse map file

### ISSUE THREAD

**Issue by lumingxijian** [HunterPie/HunterPie#486]
![HunterPie v2 2024_1_7 4_29_33](https://github.com/HunterPie/HunterPie/assets/85481400/7021da2b-79fa-43d2-ac82-9616d87a0765)

**Comment by Haato3o** [comment]
Your HunterPie is outdated. If you live in China, GFW is probably blocking your connection to my server to get the latest files. You'll have to update it manually.
https://api.hunterpie.com/v1/version/latest

**Comment by Ashesonee** [comment]
Im chinese user ,After the update is completed, the "failed to parse map file" issue still exists and cannot be used normally, still displaying this:"failed to parse map file"
![hunterpie](https://github.com/user-attachments/assets/49799075-cdbe-4071-ad4b-fe27620336df)

**Comment by lanvent** [comment]
@Ashesonee  the newest version is 2.11.0.127
