### ISSUE TITLE
[Q] [MP] [MHW] Monster & Damage meter widgets

### ISSUE THREAD

**Issue by vavavr00m** [HunterPie/HunterPie#487]
1. How do I make HunterPie show the parts without focusing/aiming on the monster? Pressing Q to display the parts brings the monster to focus and constantly moves the screen which is making me dizzy.
2. If a group has a mission to kill one large monster, HunterPie will track the total damage only for the first large monster damaged. It will stop calculating the total damage for the second large monster should a player choose to kill a different monster before completing the objective. This was also causing the damage calculation to stop if different players go to separate monsters to kill separately. How to make HunterPie track total damage for each large monster or total damage for all large monsters damaged during a mission?

**Comment by Haato3o** [comment]
> How do I make HunterPie show the parts without focusing/aiming on the monster? Pressing Q to display the parts brings the monster to focus and constantly moves the screen which is making me dizzy.

Support for other targeting methods is on its way for next release. As a workaround: change your lockon settings to turn off the focus.
![lockon-settings](https://cdn.hunterpie.com/Static/mhw-lockon-settings.png)

> If a group has a mission to kill one large monster, HunterPie will track the total damage only for the first large monster damaged. It will stop calculating the total damage for the second large monster should a player choose to kill a different monster before completing the objective. This was also causing the damage calculation to stop if different players go to separate monsters to kill separately. How to make HunterPie track total damage for each large monster or total damage for all large monsters damaged during a mission?

HunterPie does not calculate the damage, that's done by the game, it only displays the numbers. The game has limitations, it only works on quests, it only tracks damage done by monsters that are in the targets list, if the monster you're hitting is not a quest target then it won't be accounted for. It's not a HunterPie issue, it's a game limitation.
