### ISSUE TITLE
Monster Widget not showing damage

### ISSUE THREAD

**Issue by Jim-Gloaguen** [HunterPie/HunterPie#503]
Hello, i am unable to see monster's life or the damage I do to its parts like the screenshot in the patch notes. In the attached screenshot, I am at the end of a hunt (Rathian almost dead) and no info about it. Everything else in the overlay is working as expected :)

![Capture d'écran 2024-02-24 205915](https://github.com/HunterPie/HunterPie/assets/65023608/abc08fbf-b310-4a35-8829-bd4b0db1bb8c)

What I tried so far : 

- Check if I have the latest version of HunterPie (I do, you can see the beautiful longsword widget 💖)
- Uninstall and reinstall of HunterPie
- Uninstall HunterPie and reinstall in monster Hunter World folder (it was on another drive before)
- Every target option in the monster widget
- Test some other settings in monster widget
- Launching the game without any mods

I did not see any change so far with what I tried. Also this is my first time using HunterPie v2 (loved v1 too btw) so maybe I misunderstood something.

**Comment by Haato3o** [comment]
Looks like you're using the minimal theme for HunterPie, change it back to the default if you want to see the monster's health bars

**Comment by Jim-Gloaguen** [comment]
You are right ! Switched back to Default and it worked. Thanks a lot.
