### ISSUE TITLE
Unable to see monster parts or ailments

### ISSUE THREAD

**Issue by bananaqq** [HunterPie/HunterPie#508]
I am playing MHW solo and am not seeing monster parts or ailments. I checked my Monster Widget settings and have kept everything default from when installed. Enable monster parts/ailments are on and I am able to see monster hp and stamina no issue.

**Comment by Haato3o** [comment]
Only the quest host can see that information. It is a game limitation.

**Comment by bananaqq** [comment]
Correct. I understand that aspect but as a solo player, I don't understand how I am also not the quest host

**Comment by bananaqq** [comment]
![2024-03-18 11_36_12-MONSTER HUNTER_ WORLD(421652)](https://github.com/HunterPie/HunterPie/assets/163807537/c8ebb4ac-fbbe-4636-9dc9-c1de390cde63)
![2024-03-18 11_38_18-HunterPie](https://github.com/HunterPie/HunterPie/assets/163807537/07f26457-dd54-4591-b705-2880b0c32120)
