### ISSUE TITLE
Streamer Mode capture.

### ISSUE THREAD

**Issue by C4J3** [HunterPie/HunterPie#513]
So I'm trying to capture my HunterPie widgets to stream on Discord. I've tried using OBS and discord streaming itself and both don't seem to be able to capture it. I've enabled streamer mode for all the widgets I use and tried to find them in OBS with Window Capture but none come up and using the 'enable capturing thrid-party overlays' feature in OBS doesn't work either. I can't find any real mention of it in the docs other than the feature exists and for a while now the option comes up as `//Strings/Client/Settings/Setting[@ld='ENABLE_STREAMER_MODE']` and since then I've not been able to capture it at all.

Not sure if this is a bug, depreciated feature or what so any advice would be appreciated.

**Comment by Haato3o** [comment]
Streamer mode is not implemented, hence why it doesn't have a string
