### ISSUE TITLE
Monster Widget not tracking damage in mission published by friend

### ISSUE THREAD

**Issue by miscillo** [HunterPie/HunterPie#514]
As per the title, if a friend posts a mission and I join, the monster widget doesn't keep track of the damage taken by the various parts.
However, if I publish the mission and go alone or with friends, the tracker tracks the damage correctly.

It doesn't seem to be tied to a particular monster or mission.

Broken part counter and tenderized timer seems to work fine in both cases.

Is my installation having problems for some reason or is it a known bug?

**Comment by Haato3o** [comment]
It's a game limitation. Only the quest host has the monster's part information in the game's memory and it's been like that since MHW was released.

**Comment by miscillo** [comment]
oh... I didn't notice before. Ok. Thank you
