### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by GuoZhiPeng2** [HunterPie/HunterPie#522]
I can't find the widget window in the game after opening the state component, I've opened the display widget in Hunterpie and the initialization widget is also open.

**Comment by GuoZhiPeng2** [comment]
![image2](https://github.com/HunterPie/HunterPie/assets/169526120/9a56f7c6-e592-4a17-b344-a5d60b061c1c)
![Uploading image3.png…]()

**Comment by GuoZhiPeng2** [comment]
![Uploading image3.png…]()

**Comment by GuoZhiPeng2** [comment]
![image3](https://github.com/HunterPie/HunterPie/assets/169526120/063e88a4-649c-406e-b6d2-a6e6845658c6)

**Comment by Haato3o** [comment]
You're playing MHWorld but you're configuring HunterPie for MHRise. Make sure you're selecting the right game using the selection box on the top left of your settings window.

![image](https://github.com/HunterPie/HunterPie/assets/35552782/ac45852f-8ba2-44da-8046-f4347970f846)

Also, you **must** restart HunterPie after creating and configuring your abnormalities tray.

**Comment by GuoZhiPeng2** [comment]
Thanks, here's my problem, I didn't find this option, sorry
