### ISSUE TITLE
Online Play Connectivity Issue

### ISSUE THREAD

**Issue by brandrewsss** [HunterPie/HunterPie#540]
New user here playing Monster Hunter World with Iceborne DLC. As soon as I began using HunterPie I constantly get disconnected from Online Play. I can’t hold a lobby for more than 2 minutes, and while I can reconnect I get disconnected just as fast.

The only fix I have found is a Modem & Router reset. This will then allow me to use HunterPie and maintain a session until I close the game. At which point I need another reset before I can play on a stable connection again.

**Comment by Haato3o** [comment]
HunterPie has no influence in your connection, so it is impossible for it to be the reason of your disconnects. 
If you're playing on fullscreen and been alt tabbing a lot, that's the reason. MHW has a bug that can disconnect you from online sessions if you alt tab, capcom has never bothered to fix it and the only solution is to play on borderless windowed.

**Comment by brandrewsss** [comment]
@Haato3o - Could you please delete this issue from the repository?
