### ISSUE TITLE
MH World : SteamWorks Natural Steam Max Value for the gauge is wrong

### ISSUE THREAD

**Issue by MegaJulien** [HunterPie/HunterPie#541]
The bar that shows how full the Natural Steam is has a max value of 600, but the cap is at 700.
![image](https://github.com/user-attachments/assets/4b1e7001-e1d6-4b5a-b9fd-828809b9915d) here is at 570(almost full)

![image](https://github.com/user-attachments/assets/601fc926-ca0a-46c3-879c-d283a43d2a92) here is 700(max but the bar is already full at 600)

**Comment by Haato3o** [comment]
Hmm, in the code the max is hardcoded as 700, so it's probably some UI bug. I'll look into it
