### ISSUE TITLE
Latest Version Error for MHW Build 421471

### ISSUE THREAD

**Issue by igiespiritu** [HunterPie/HunterPie#562]
HunterPie version 2.9 is working great but when I updated to the latest version (2.11), it showed some error about missing addresses and offsets.

I tried adding the missing addresses and offsets on to the map file (MonsterHunterWorld.421471.map) and errors are now gone, but when I started a quest, errors shows up and overlay doesn't show. attaching the LogFile and updated map file here
[HunterPie_Log.txt](https://github.com/user-attachments/files/17532890/HunterPie_Log.txt)
[MonsterHunterWorld.421471.map.txt](https://github.com/user-attachments/files/17532902/MonsterHunterWorld.421471.map.txt)

Hope to be able to use the latest version on my MHW Build

**Comment by Haato3o** [comment]
The game build 421471 is **not** the latest version of the game and therefore will not be supported. Either use an older version of HunterPie or update your game.

**Comment by VaelophisNyx** [comment]
fun information: updating the game doesn't work with ICE mod (dev seems to not want to bother)
but, hunterpie will not run on a back-dated game :)
literally no version will, I've tried

So what are we to do? Just not use it? Forever scorned for daring to want a better experience?
